# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZJModuleCommon' do
 pod 'SDWebImage', '~> 5.0'
 pod 'Masonry', '~> 1.1.0'
 pod 'MBProgressHUD', '~> 1.1.0'
 pod 'YTKNetwork', '~> 2.1.4'
 pod 'Reachability', '~> 3.2'
end
