# Uncomment the next line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git
 source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'ZJModuleCommon' do
 pod 'SDWebImage', '~> 5.0'
 pod 'Masonry', '1.1.0'
 pod 'MBProgressHUD', '~> 1.1.0'
 pod 'YTKNetwork', '~> 2.1.4'
 pod 'Reachability', '~> 3.2'
 pod 'JKCategories', '~> 1.9'
end

# 加入这些配置
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "Masonry"
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
